import { SoilType, Language, ForecastDuration } from './types';

export const SOIL_TYPES: SoilType[] = [
  SoilType.ALLUVIAL,
  SoilType.BLACK,
  SoilType.RED,
  SoilType.LATERITE,
  SoilType.ARID,
  SoilType.FOREST,
];

export const FORECAST_DURATIONS: ForecastDuration[] = [
  ForecastDuration.SIX_MONTHS,
  ForecastDuration.TWELVE_MONTHS,
];

export const SOIL_TYPE_TRANSLATIONS: Record<SoilType, Record<Language, string>> = {
  [SoilType.ALLUVIAL]: {
    [Language.ENGLISH]: 'Alluvial',
    [Language.HINDI]: 'जलोढ़',
    [Language.TAMIL]: 'வண்டல்',
    [Language.TELUGU]: 'ఒండ్రు',
    [Language.KANNADA]: 'ಮೆಕ್ಕಲು',
    [Language.BENGALI]: 'পলিমাটি',
    [Language.MARATHI]: 'गाळाची',
    [Language.PUNJABI]: 'ਜਲੋੜ੍ਹ',
  },
  [SoilType.BLACK]: {
    [Language.ENGLISH]: 'Black',
    [Language.HINDI]: 'काली',
    [Language.TAMIL]: 'கரிசல்',
    [Language.TELUGU]: 'నల్ల రేగడి',
    [Language.KANNADA]: 'ಕಪ್ಪು',
    [Language.BENGALI]: 'কালো',
    [Language.MARATHI]: 'काळी',
    [Language.PUNJABI]: 'ਕਾਲੀ',
  },
  [SoilType.RED]: {
    [Language.ENGLISH]: 'Red',
    [Language.HINDI]: 'लाल',
    [Language.TAMIL]: 'செம்மண்',
    [Language.TELUGU]: 'ఎర్ర',
    [Language.KANNADA]: 'ಕೆಂಪು',
    [Language.BENGALI]: 'লাল',
    [Language.MARATHI]: 'लाल',
    [Language.PUNJABI]: 'ਲਾਲ',
  },
  [SoilType.LATERITE]: {
    [Language.ENGLISH]: 'Laterite',
    [Language.HINDI]: 'लैटेराइट',
    [Language.TAMIL]: 'சரளை',
    [Language.TELUGU]: 'లేటరైట్',
    [Language.KANNADA]: 'ಲ್ಯಾಟರೈಟ್',
    [Language.BENGALI]: 'ল্যাটেরাইট',
    [Language.MARATHI]: 'जांभी',
    [Language.PUNJABI]: 'ਲੈਟਰਾਈਟ',
  },
  [SoilType.ARID]: {
    [Language.ENGLISH]: 'Arid',
    [Language.HINDI]: 'शुष्क',
    [Language.TAMIL]: 'வறண்ட',
    [Language.TELUGU]: 'శుష్క',
    [Language.KANNADA]: 'ಶುಷ್ಕ',
    [Language.BENGALI]: 'শুষ্ক',
    [Language.MARATHI]: 'शुष्क',
    [Language.PUNJABI]: 'ਸੁੱਕੀ',
  },
  [SoilType.FOREST]: {
    [Language.ENGLISH]: 'Forest',
    [Language.HINDI]: 'वन',
    [Language.TAMIL]: 'காடு',
    [Language.TELUGU]: 'అటవీ',
    [Language.KANNADA]: 'అరణ్య',
    [Language.BENGALI]: 'বন',
    [Language.MARATHI]: 'वन',
    [Language.PUNJABI]: 'ਜੰਗਲੀ',
  },
};

export const UI_TEXT = {
  [Language.ENGLISH]: {
    title: "GrowFuse",
    subtitle: "AI-Powered Crop Intelligence for Indian Farmers",
    locationLabel: "Location (City/Pincode)",
    locationPlaceholder: "e.g., Nagpur or 440001",
    soilTypeLabel: "Soil Type",
    selectSoilType: "Select a soil type",
    landAreaLabel: "Land Area (in acres)",
    landAreaPlaceholder: "e.g., 5.5",
    getRecommendations: "Get Recommendations",
    recommendationsTitle: "Top 5 Crop Recommendations",
    noResults: "Enter your farm details above to get AI-powered crop recommendations.",
    loading: "Analyzing your farm data...",
    error: "An error occurred. Please try again.",
    confidence: "Confidence",
    forecastPeriodLabel: "Forecast Period",
    sixMonths: "Next 6 Months",
    twelveMonths: "Next 12 Months",
    history: "History",
    recommendationHistory: "Recommendation History",
    noHistory: "You have no saved recommendations yet. Get a new recommendation and it will appear here automatically.",
    saveToHistory: "Save to History",
    recommendationSaved: "Saved!",
    nameYourRecommendation: "Name your recommendation (optional)",
    recommendationNamePlaceholder: "e.g., North Field - Summer",
    save: "Save",
    cancel: "Cancel",
    inputs: "Inputs",
    recommendations: "Recommendations",
    welcome: "Welcome",
    myFarms: "My Farms",
    addFarm: "Add Farm",
    noFarms: "You haven't added any farms yet. Click 'Add Farm' to get started.",
    soilSuffix: "Soil",
    savedRecommendations: "Saved Recommendations",
    noSavedRecommendations: "No recommendations saved for this farm yet.",
    farmName: "Farm Name",
    farmNamePlaceholder: "e.g., North Field",
    saveFarm: "Save Farm",
    invalidPhone: "Please enter a valid 10-digit phone number.",
    invalidOtp: "Invalid OTP. Please try again.",
    enterPhoneNumber: "Enter your phone number",
    phonePlaceholder: "10-digit mobile number",
    sendOtp: "Send OTP",
    enterOtp: "Enter OTP",
    otpSent: "An OTP has been sent to your number.",
    otpPlaceholder: "6-digit OTP",
    verifyAndSignIn: "Verify & Sign In",
    resendOtp: "Resend OTP",
  },
  [Language.HINDI]: {
    title: "GrowFuse",
    subtitle: "भारतीय किसानों के लिए एआई-संचालित फसल इंटेलिजेंस",
    locationLabel: "स्थान (शहर/पिनकोड)",
    locationPlaceholder: "उदा., नागपुर या 440001",
    soilTypeLabel: "मिट्टी का प्रकार",
    selectSoilType: "एक मिट्टी का प्रकार चुनें",
    landAreaLabel: "भूमि क्षेत्र (एकड़ में)",
    landAreaPlaceholder: "उदा., 5.5",
    getRecommendations: "सिफारिशें प्राप्त करें",
    recommendationsTitle: "शीर्ष 5 फसल सिफारिशें",
    noResults: "एआई-संचालित फसल सिफारिशें प्राप्त करने के लिए ऊपर अपने खेत का विवरण दर्ज करें।",
    loading: "आपके खेत के डेटा का विश्लेषण किया जा रहा है...",
    error: "एक त्रुटि हुई। कृपया पुन: प्रयास करें।",
    confidence: "आत्मविश्वास",
    forecastPeriodLabel: "पूर्वानुमान अवधि",
    sixMonths: "अगले 6 महीने",
    twelveMonths: "अगले 12 महीने",
    history: "इतिहास",
    recommendationHistory: "सिफारिश का इतिहास",
    noHistory: "आपके पास अभी तक कोई सहेजी गई सिफारिश नहीं है। एक नई सिफारिश प्राप्त करें और यह स्वचालित रूप से यहां दिखाई देगी।",
    saveToHistory: "इतिहास में सहेजें",
    recommendationSaved: "सहेजा गया!",
    nameYourRecommendation: "अपनी सिफारिश को नाम दें (वैकल्पिक)",
    recommendationNamePlaceholder: "उदा., उत्तरी खेत - गर्मी",
    save: "सहेजें",
    cancel: "रद्द करें",
    inputs: "इनपुट",
    recommendations: "सिफारिशें",
    welcome: "आपका स्वागत है",
    myFarms: "मेरे खेत",
    addFarm: "खेत जोड़ें",
    noFarms: "आपने अभी तक कोई खेत नहीं जोड़ा है। शुरू करने के लिए 'खेत जोड़ें' पर क्लिक करें।",
    soilSuffix: "मिट्टी",
    savedRecommendations: "सहेजी गई सिफारिशें",
    noSavedRecommendations: "इस खेत के लिए अभी तक कोई सिफारिश नहीं सहेजी गई है।",
    farmName: "खेत का नाम",
    farmNamePlaceholder: "उदा., उत्तरी खेत",
    saveFarm: "खेत सहेजें",
    invalidPhone: "कृपया एक मान्य 10-अंकीय फ़ोन नंबर दर्ज करें।",
    invalidOtp: "अमान्य ओटीपी। कृपया पुन: प्रयास करें।",
    enterPhoneNumber: "अपना फ़ोन नंबर दर्ज करें",
    phonePlaceholder: "10-अंकीय मोबाइल नंबर",
    sendOtp: "ओटीपी भेजें",
    enterOtp: "ओटीपी दर्ज करें",
    otpSent: "आपके नंबर पर एक ओटीपी भेजा गया है।",
    otpPlaceholder: "6-अंकीय ओटीपी",
    verifyAndSignIn: "सत्यापित करें और साइन इन करें",
    resendOtp: "ओटीपी फिर से भेजें",
  },
  [Language.TAMIL]: {
    title: "GrowFuse",
    subtitle: "இந்திய விவசாயிகளுக்கான AI-இயங்கும் பயிர் நுண்ணறிவு",
    locationLabel: "இடம் (நகரம்/பின்கோடு)",
    locationPlaceholder: "எ.கா., நாக்பூர் அல்லது 440001",
    soilTypeLabel: "மண் வகை",
    selectSoilType: "ஒரு மண் வகையைத் தேர்ந்தெடுக்கவும்",
    landAreaLabel: "நிலப் பகுதி (ஏக்கரில்)",
    landAreaPlaceholder: "எ.கா., 5.5",
    getRecommendations: "பரிந்துரைகளைப் பெறுக",
    recommendationsTitle: "சிறந்த 5 பயிர் பரிந்துரைகள்",
    noResults: "AI-இயங்கும் பயிர் பரிந்துரைகளைப் பெற மேலே உங்கள் பண்ணை விவரங்களை உள்ளிடவும்.",
    loading: "உங்கள் பண்ணை தரவை பகுப்பாய்வு செய்கிறது...",
    error: "ஒரு பிழை ஏற்பட்டது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
    confidence: "நம்பிக்கை",
    forecastPeriodLabel: "முன்கணிப்பு காலம்",
    sixMonths: "அடுத்த 6 மாதங்கள்",
    twelveMonths: "அடுத்த 12 மாதங்கள்",
    history: "வரலாறு",
    recommendationHistory: "பரிந்துரை வரலாறு",
    noHistory: "உங்களிடம் சேமிக்கப்பட்ட பரிந்துரைகள் எதுவும் இல்லை. புதிய பரிந்துரையைப் பெற்றால் அது தானாகவே இங்கே தோன்றும்.",
    saveToHistory: "வரலாற்றில் சேமி",
    recommendationSaved: "சேமிக்கப்பட்டது!",
    nameYourRecommendation: "உங்கள் பரிந்துரைக்கு பெயரிடுங்கள் (விருப்ப)",
    recommendationNamePlaceholder: "எ.கா., வடக்கு புலம் - கோடை",
    save: "சேமி",
    cancel: "ரத்துசெய்",
    inputs: "உள்ளீடுகள்",
    recommendations: "பரிந்துரைகள்",
    welcome: "வரவேற்கிறோம்",
    myFarms: "என் பண்ணைகள்",
    addFarm: "பண்ணையைச் சேர்",
    noFarms: "நீங்கள் இன்னும் பண்ணைகளைச் சேர்க்கவில்லை. தொடங்குவதற்கு 'பண்ணையைச் சேர்' என்பதைக் கிளிக் செய்க.",
    soilSuffix: "மண்",
    savedRecommendations: "சேமித்த பரிந்துரைகள்",
    noSavedRecommendations: "இந்தப் பண்ணைக்கு இன்னும் பரிந்துரைகள் எதுவும் சேமிக்கப்படவில்லை.",
    farmName: "பண்ணையின் பெயர்",
    farmNamePlaceholder: "எ.கா., வடக்கு புலம்",
    saveFarm: "பண்ணையைச் சேமி",
    invalidPhone: "சரியான 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்.",
    invalidOtp: "தவறான OTP. மீண்டும் முயற்சிக்கவும்.",
    enterPhoneNumber: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
    phonePlaceholder: "10-இலக்க மொபைல் எண்",
    sendOtp: "OTP அனுப்பு",
    enterOtp: "OTP ஐ உள்ளிடவும்",
    otpSent: "உங்கள் எண்ணுக்கு ஒரு OTP அனுப்பப்பட்டுள்ளது.",
    otpPlaceholder: "6-இலக்க OTP",
    verifyAndSignIn: "சரிபார்த்து உள்நுழையவும்",
    resendOtp: "OTP ஐ மீண்டும் அனுப்பு",
  },
  [Language.TELUGU]: {
    title: "GrowFuse",
    subtitle: "భారతీయ రైతుల కోసం AI-ఆధారిత పంట ఇంటెలిజెన్స్",
    locationLabel: "ప్రదేశం (నగరం/పిన్‌కోడ్)",
    locationPlaceholder: "ఉదా., నాగ్‌పూర్ లేదా 440001",
    soilTypeLabel: "నేల రకం",
    selectSoilType: "నేల రకాన్ని ఎంచుకోండి",
    landAreaLabel: "భూమి వైశాల్యం (ఎకరాలలో)",
    landAreaPlaceholder: "ఉదా., 5.5",
    getRecommendations: "సిఫార్సులను పొందండి",
    recommendationsTitle: "టాప్ 5 పంట సిఫార్సులు",
    noResults: "AI-ఆధారిత పంట సిఫార్సులను పొందడానికి పైన మీ వ్యవసాయ వివరాలను నమోదు చేయండి.",
    loading: "మీ వ్యవసాయ డేటాను విశ్లేషిస్తోంది...",
    error: "లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    confidence: "విశ్వాసం",
    forecastPeriodLabel: "వాతావరణ సూచన కాలం",
    sixMonths: "తదుపరి 6 నెలలు",
    twelveMonths: "తదుపరి 12 నెలలు",
    history: "చరిత్ర",
    recommendationHistory: "సిఫార్సు చరిత్ర",
    noHistory: "మీకు ఇంకా సేవ్ చేయబడిన సిఫార్సులు లేవు. కొత్త సిఫార్సును పొందండి మరియు అది స్వయంచాలకంగా ఇక్కడ కనిపిస్తుంది.",
    saveToHistory: "చరిత్రలో సేవ్ చేయండి",
    recommendationSaved: "సేవ్ చేయబడింది!",
    nameYourRecommendation: "మీ సిఫార్సుకు పేరు పెట్టండి (ఐచ్ఛికం)",
    recommendationNamePlaceholder: "ఉదా., ఉత్తర క్షేత్రం - వేసవి",
    save: "సేవ్ చేయండి",
    cancel: "రద్దు చేయండి",
    inputs: "ఇన్‌పుట్‌లు",
    recommendations: "సిఫార్సులు",
    welcome: "స్వాగతం",
    myFarms: "నా పొలాలు",
    addFarm: "పొలం జోడించు",
    noFarms: "మీరు ఇంకా ఏ పొలాలను జోడించలేదు. ప్రారంభించడానికి 'పొలం జోడించు' క్లిక్ చేయండి.",
    soilSuffix: "నేల",
    savedRecommendations: "సేవ్ చేసిన సిఫార్సులు",
    noSavedRecommendations: "ఈ పొలం కోసం ఇంకా సిఫార్సులు సేవ్ చేయబడలేదు.",
    farmName: "పొలం పేరు",
    farmNamePlaceholder: "ఉదా., ఉత్తర క్షేత్రం",
    saveFarm: "పొలం సేవ్ చేయి",
    invalidPhone: "దయచేసి చెల్లుబాటు అయ్యే 10-అంకెల ఫోన్ నంబర్‌ను నమోదు చేయండి.",
    invalidOtp: "చెల్లని OTP. దయచేసి మళ్లీ ప్రయత్నించండి.",
    enterPhoneNumber: "మీ ఫోన్ నంబర్‌ను నమోదు చేయండి",
    phonePlaceholder: "10-అంకెల మొబైల్ నంబర్",
    sendOtp: "OTP పంపండి",
    enterOtp: "OTP నమోదు చేయండి",
    otpSent: "మీ నంబర్‌కు OTP పంపబడింది.",
    otpPlaceholder: "6-అంకెల OTP",
    verifyAndSignIn: "ధృవీకరించి, సైన్ ఇన్ చేయండి",
    resendOtp: "OTPని మళ్లీ పంపండి",
  },
  [Language.KANNADA]: {
    title: "GrowFuse",
    subtitle: "ಭಾರತೀಯ ರೈತರಿಗಾಗಿ AI-ಚಾಲಿತ ಬೆಳೆ ಬುದ್ಧಿಮತ್ತೆ",
    locationLabel: "ಸ್ಥಳ (ನಗರ/ಪಿನ್‌ಕೋಡ್)",
    locationPlaceholder: "ಉದಾ., ನಾಗ್ಪುರ ಅಥವಾ 440001",
    soilTypeLabel: "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
    selectSoilType: "ಮಣ್ಣಿನ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    landAreaLabel: "ಭೂಪ್ರದೇಶ (ಎಕರೆಗಳಲ್ಲಿ)",
    landAreaPlaceholder: "ಉದಾ., 5.5",
    getRecommendations: "ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ",
    recommendationsTitle: "ಟಾಪ್ 5 ಬೆಳೆ ಶಿಫಾರಸುಗಳು",
    noResults: "AI-ಚಾಲಿತ ಬೆಳೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕೃಷಿ ವಿವರಗಳನ್ನು ಮೇಲೆ ನಮೂದಿಸಿ.",
    loading: "ನಿಮ್ಮ ಕೃಷಿ ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    error: "ಒಂದು ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    confidence: "ವಿಶ್ವಾಸ",
    forecastPeriodLabel: "ಮುನ್ಸೂಚನೆ ಅವಧಿ",
    sixMonths: "ಮುಂದಿನ 6 ತಿಂಗಳುಗಳು",
    twelveMonths: "ಮುಂದಿನ 12 ತಿಂಗಳುಗಳು",
    history: "ಇತಿಹಾಸ",
    recommendationHistory: "ಶಿಫಾರಸು ಇತಿಹಾಸ",
    noHistory: "ನೀವು ಯಾವುದೇ ಉಳಿಸಿದ ಶಿಫಾರಸುಗಳನ್ನು ಹೊಂದಿಲ್ಲ. ಹೊಸ ಶಿಫಾರಸನ್ನು ಪಡೆದರೆ ಅದು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
    saveToHistory: "ಇತಿಹಾಸಕ್ಕೆ ಉಳಿಸಿ",
    recommendationSaved: "ಉಳಿಸಲಾಗಿದೆ!",
    nameYourRecommendation: "ನಿಮ್ಮ ಶಿಫಾರಸಿಗೆ ಹೆಸರಿಸಿ (ಐಚ್ಛಿಕ)",
    recommendationNamePlaceholder: "ಉದಾ., ಉತ್ತರ ಕ್ಷೇತ್ರ - ಬೇಸಿಗೆ",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    inputs: "ಇನ್‌ಪುಟ್‌ಗಳು",
    recommendations: "ಶಿಫಾರಸುಗಳು",
    welcome: "ಸ್ವಾಗತ",
    myFarms: "ನನ್ನ ಹೊಲಗಳು",
    addFarm: "ಹೊಲ ಸೇರಿಸಿ",
    noFarms: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಹೊಲಗಳನ್ನು ಸೇರಿಸಿಲ್ಲ. ಪ್ರಾರಂಭಿಸಲು 'ಹೊಲ ಸೇರಿಸಿ' ಕ್ಲಿಕ್ ಮಾಡಿ.",
    soilSuffix: "ಮಣ್ಣು",
    savedRecommendations: "ಉಳಿಸಿದ ಶಿಫಾರಸುಗಳು",
    noSavedRecommendations: "ಈ ಹೊಲಕ್ಕೆ ಯಾವುದೇ ಶಿಫಾರಸುಗಳನ್ನು ಇನ್ನೂ ಉಳಿಸಲಾಗಿಲ್ಲ.",
    farmName: "ಹೊಲದ ಹೆಸರು",
    farmNamePlaceholder: "ಉದಾ., ಉತ್ತರ ಕ್ಷೇತ್ರ",
    saveFarm: "ಹೊಲ ಉಳಿಸಿ",
    invalidPhone: "ದಯವಿಟ್ಟು ಮಾನ್ಯ 10-ಅಂಕಿಯ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    invalidOtp: "ಅಮಾನ್ಯ OTP. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    enterPhoneNumber: "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    phonePlaceholder: "10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    enterOtp: "OTP ನಮೂದಿಸಿ",
    otpSent: "ನಿಮ್ಮ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ.",
    otpPlaceholder: "6-ಅಂಕಿಯ OTP",
    verifyAndSignIn: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಇನ್ ಮಾಡಿ",
    resendOtp: "OTP ಮರುಕಳುಹಿಸಿ",
  },
  [Language.BENGALI]: {
    title: "GrowFuse",
    subtitle: "ভারতীয় কৃষকদের জন্য এআই-চালিত ফসল বুদ্ধিমত্তা",
    locationLabel: "অবস্থান (শহর/পিনকোড)",
    locationPlaceholder: "যেমন, নাগপুর বা 440001",
    soilTypeLabel: "মাটির ধরন",
    selectSoilType: "মাটির ধরন নির্বাচন করুন",
    landAreaLabel: "জমির পরিমাণ (একরে)",
    landAreaPlaceholder: "যেমন, 5.5",
    getRecommendations: "সুপারিশ পান",
    recommendationsTitle: "শীর্ষ ৫টি ফসল সুপারিশ",
    noResults: "এআই-চালিত ফসল সুপারিশ পেতে উপরে আপনার খামারের বিবরণ লিখুন।",
    loading: "আপনার খামারের ডেটা বিশ্লেষণ করা হচ্ছে...",
    error: "একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    confidence: "আত্মবিশ্বাস",
    forecastPeriodLabel: "পূর্বাভাস সময়কাল",
    sixMonths: "পরবর্তী ৬ মাস",
    twelveMonths: "পরবর্তী ১২ মাস",
    history: "ইতিহাস",
    recommendationHistory: "সুপারিশের ইতিহাস",
    noHistory: "আপনার কোনো সংরক্ষিত সুপারিশ নেই। একটি নতুন সুপারিশ পান এবং এটি স্বয়ংক্রিয়ভাবে এখানে উপস্থিত হবে।",
    saveToHistory: "ইতিহাসে সংরক্ষণ করুন",
    recommendationSaved: "সংরক্ষিত হয়েছে!",
    nameYourRecommendation: "আপনার সুপারিশের নাম দিন (ঐচ্ছিক)",
    recommendationNamePlaceholder: "যেমন, উত্তর ফিল্ড - গ্রীষ্ম",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    inputs: "ইনপুট",
    recommendations: "সুপারিশ",
    welcome: "স্বাগতম",
    myFarms: "আমার খামার",
    addFarm: "খামার যোগ করুন",
    noFarms: "আপনি এখনও কোনো খামার যোগ করেননি। শুরু করতে 'খামার যোগ করুন' ক্লিক করুন।",
    soilSuffix: "মাটি",
    savedRecommendations: "সংরক্ষিত সুপারিশ",
    noSavedRecommendations: "এই খামারের জন্য এখনো কোনো সুপারিশ সংরক্ষণ করা হয়নি।",
    farmName: "খামারের নাম",
    farmNamePlaceholder: "যেমন, উত্তর ফিল্ড",
    saveFarm: "খামার সংরক্ষণ করুন",
    invalidPhone: "অনুগ্রহ করে একটি বৈধ ১০-সংখ্যার ফোন নম্বর লিখুন।",
    invalidOtp: "অবৈধ OTP। অনুগ্রহ করে আবার চেষ্টা করুন।",
    enterPhoneNumber: "আপনার ফোন নম্বর লিখুন",
    phonePlaceholder: "১০-সংখ্যার মোবাইল নম্বর",
    sendOtp: "OTP পাঠান",
    enterOtp: "OTP লিখুন",
    otpSent: "আপনার নম্বরে একটি OTP পাঠানো হয়েছে।",
    otpPlaceholder: "৬-সংখ্যার OTP",
    verifyAndSignIn: "যাচাই করুন এবং সাইন ইন করুন",
    resendOtp: "OTP আবার পাঠান",
  },
  [Language.MARATHI]: {
    title: "GrowFuse",
    subtitle: "भारतीय शेतकऱ्यांसाठी एआय-आधारित पीक बुद्धिमत्ता",
    locationLabel: "स्थान (शहर/पिनकोड)",
    locationPlaceholder: "उदा., नागपूर किंवा 440001",
    soilTypeLabel: "मातीचा प्रकार",
    selectSoilType: "मातीचा प्रकार निवडा",
    landAreaLabel: "जमिनीचे क्षेत्र (एकरमध्ये)",
    landAreaPlaceholder: "उदा., 5.5",
    getRecommendations: "शिफारसी मिळवा",
    recommendationsTitle: "शीर्ष ५ पीक शिफारसी",
    noResults: "एआय-आधारित पीक शिफारसी मिळवण्यासाठी वर तुमच्या शेतीचा तपशील प्रविष्ट करा.",
    loading: "तुमच्या शेतीच्या डेटाचे विश्लेषण करत आहे...",
    error: "एक त्रुटी आली आहे. कृपया पुन्हा प्रयत्न करा.",
    confidence: "आत्मविश्वास",
    forecastPeriodLabel: "अंदाज कालावधी",
    sixMonths: "पुढील 6 महिने",
    twelveMonths: "पुढील 12 महिने",
    history: "इतिहास",
    recommendationHistory: "शिफारस इतिहास",
    noHistory: "तुमच्याकडे कोणतीही जतन केलेली शिफारस नाही. नवीन शिफारस मिळवा आणि ती आपोआप येथे दिसेल.",
    saveToHistory: "इतिहासामध्ये जतन करा",
    recommendationSaved: "जतन केले!",
    nameYourRecommendation: "तुमच्या शिफारसीला नाव द्या (पर्यायी)",
    recommendationNamePlaceholder: "उदा., उत्तर शेत - उन्हाळा",
    save: "जतन करा",
    cancel: "रद्द करा",
    inputs: "इनपुट",
    recommendations: "शिफारसी",
    welcome: "स्वागत आहे",
    myFarms: "माझी शेती",
    addFarm: "शेत जोडा",
    noFarms: "तुम्ही अद्याप कोणतीही शेती जोडलेली नाही. सुरू करण्यासाठी 'शेत जोडा' वर क्लिक करा.",
    soilSuffix: "माती",
    savedRecommendations: "जतन केलेल्या शिफारसी",
    noSavedRecommendations: "या शेतासाठी अद्याप कोणत्याही शिफारसी जतन केल्या नाहीत.",
    farmName: "शेताचे नाव",
    farmNamePlaceholder: "उदा., उत्तर शेत",
    saveFarm: "शेत जतन करा",
    invalidPhone: "कृपया वैध १०-अंकी फोन नंबर प्रविष्ट करा.",
    invalidOtp: "अवैध OTP. कृपया पुन्हा प्रयत्न करा.",
    enterPhoneNumber: "तुमचा फोन नंबर प्रविष्ट करा",
    phonePlaceholder: "१०-अंकी मोबाईल नंबर",
    sendOtp: "OTP पाठवा",
    enterOtp: "OTP प्रविष्ट करा",
    otpSent: "तुमच्या नंबरवर एक OTP पाठवला आहे.",
    otpPlaceholder: "६-अंकी OTP",
    verifyAndSignIn: "सत्यापित करा आणि साइन इन करा",
    resendOtp: "OTP पुन्हा पाठवा",
  },
  [Language.PUNJABI]: {
    title: "GrowFuse",
    subtitle: "ਭਾਰਤੀ ਕਿਸਾਨਾਂ ਲਈ ਏਆਈ-ਸੰਚਾਲਿਤ ਫਸਲ ਇੰਟੈਲੀਜੈਂਸ",
    locationLabel: "ਸਥਾਨ (ਸ਼ਹਿਰ/ਪਿਨਕੋਡ)",
    locationPlaceholder: "ਜਿਵੇਂ, ਨਾਗਪੁਰ ਜਾਂ 440001",
    soilTypeLabel: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    selectSoilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    landAreaLabel: "ਜ਼ਮੀਨ ਦਾ ਖੇਤਰ (ਏਕੜ ਵਿੱਚ)",
    landAreaPlaceholder: "ਜਿਵੇਂ, 5.5",
    getRecommendations: "ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    recommendationsTitle: "ਸਿਖਰ 5 ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ",
    noResults: "ਏਆਈ-ਸੰਚਾਲਿਤ ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਉੱਪਰ ਆਪਣੇ ਖੇਤ ਦੇ ਵੇਰਵੇ ਦਰਜ ਕਰੋ।",
    loading: "ਤੁਹਾਡੇ ਖੇਤ ਦੇ ਡੇਟਾ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    error: "ਇੱਕ ਗਲਤੀ ਹੋਈ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    confidence: "ਆਤਮ-ਵਿਸ਼ਵਾਸ",
    forecastPeriodLabel: "ਪੂਰਵ-ਅਨੁਮਾਨ ਦੀ ਮਿਆਦ",
    sixMonths: "ਅਗਲੇ 6 ਮਹੀਨੇ",
    twelveMonths: "ਅਗਲੇ 12 ਮਹੀਨੇ",
    history: "ਇਤਿਹਾਸ",
    recommendationHistory: "ਸਿਫਾਰਸ਼ ਦਾ ਇਤਿਹਾਸ",
    noHistory: "ਤੁਹਾਡੇ ਕੋਲ ਕੋਈ ਸੁਰੱਖਿਅਤ ਕੀਤੀ ਸਿਫਾਰਸ਼ ਨਹੀਂ ਹੈ। ਇੱਕ ਨਵੀਂ ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ ਅਤੇ ਇਹ ਆਪਣੇ-ਆਪ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗੀ।",
    saveToHistory: "ਇਤਿਹਾਸ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    recommendationSaved: "ਸੁਰੱਖਿਅਤ ਹੋ ਗਈ!",
    nameYourRecommendation: "ਆਪਣੀ ਸਿਫਾਰਸ਼ ਨੂੰ ਨਾਮ ਦਿਓ (ਵਿਕਲਪਿਕ)",
    recommendationNamePlaceholder: "ਜਿਵੇਂ, ਉੱਤਰੀ ਖੇਤ - ਗਰਮੀਆਂ",
    save: "ਸੁਰੱਖਿਅਤ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    inputs: "ਇਨਪੁਟਸ",
    recommendations: "ਸਿਫਾਰਸ਼ਾਂ",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    myFarms: "ਮੇਰੇ ਖੇਤ",
    addFarm: "ਖੇਤ ਸ਼ਾਮਲ ਕਰੋ",
    noFarms: "ਤੁਸੀਂ ਹਾਲੇ ਤੱਕ ਕੋਈ ਖੇਤ ਸ਼ਾਮਲ ਨਹੀਂ ਕੀਤਾ ਹੈ। ਸ਼ੁਰੂ ਕਰਨ ਲਈ 'ਖੇਤ ਸ਼ਾਮਲ ਕਰੋ' 'ਤੇ ਕਲਿੱਕ ਕਰੋ।",
    soilSuffix: "ਮਿੱਟੀ",
    savedRecommendations: "ਸੁਰੱਖਿਅਤ ਸਿਫਾਰਸ਼ਾਂ",
    noSavedRecommendations: "ਇਸ ਖੇਤ ਲਈ ਅਜੇ ਕੋਈ ਸਿਫਾਰਸ਼ਾਂ ਸੁਰੱਖਿਅਤ ਨਹੀਂ ਹਨ।",
    farmName: "ਖੇਤ ਦਾ ਨਾਮ",
    farmNamePlaceholder: "ਜਿਵੇਂ, ਉੱਤਰੀ ਖੇਤ",
    saveFarm: "ਖੇਤ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    invalidPhone: "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 10-ਅੰਕਾਂ ਦਾ ਫ਼ੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ।",
    invalidOtp: "ਅਵੈਧ OTP। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    enterPhoneNumber: "ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
    phonePlaceholder: "10-ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ",
    sendOtp: "OTP ਭੇਜੋ",
    enterOtp: "OTP ਦਾਖਲ ਕਰੋ",
    otpSent: "ਤੁਹਾਡੇ ਨੰਬਰ 'ਤੇ ਇੱਕ OTP ਭੇਜਿਆ ਗਿਆ ਹੈ।",
    otpPlaceholder: "6-ਅੰਕਾਂ ਦਾ OTP",
    verifyAndSignIn: "ਤਸਦੀਕ ਕਰੋ ਅਤੇ ਸਾਈਨ ਇਨ ਕਰੋ",
    resendOtp: "OTP ਦੁਬਾਰਾ ਭੇਜੋ",
  },
};